name: CI/CD Pipeline Multiregion

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT: "767397849711"

jobs:
  ci-terraform-pre-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Tree Repository
        run: tree .
        working-directory: ./pre-deployment

      - name: Terraform Format Check
        run: terraform fmt --recursive --check
        working-directory: ./pre-deployment

      - name: Terraform Init
        run: terraform init -backend-config=environment/backend.tfvars
        working-directory: ./pre-deployment
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCS_SA_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

  ci-terraform-post-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Tree Repository
        run: tree .
        working-directory: ./post-deployment

      - name: Terraform Format Check
        run: terraform fmt --recursive --check
        working-directory: ./post-deployment

      - name: Terraform Init
        run: terraform init -backend-config=environment/backend.tfvars
        working-directory: ./post-deployment
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCS_SA_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
